spring.application.name=catcafe

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=${PORT:8080}

# Supabase storage
supabase.endpoint=${SUPABASE_STORAGE_ENDPOINT}
supabase.access-key=${SUPABASE_STORAGE_KEY}
supabase.secret-key=${SUPABASE_STORAGE_SECRET}
supabase.bucket-name=${SUPABASE_BUCKET_NAME}
